/* project_runeos.c — Project HTML embedded in the kernel */

const char *project_runeos_html =
"<!-- FILE: projects/runeos/index.html -->\n"
"<!DOCTYPE html>\n"
"<html lang=\"en\">\n"
"<head>\n"
"<meta charset=\"UTF-8\">\n"
"<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
"<title>RuneOS v2.0</title>\n"
"<style>\n"
"*, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }\n"
"body {\n"
"  font-family: 'Inter', system-ui, sans-serif;\n"
"  background: #0d0d0d;\n"
"  color: #e8e8e8;\n"
"  line-height: 1.65;\n"
"  overflow-y: auto;\n"
"  -webkit-font-smoothing: antialiased;\n"
"}\n"
"::selection { background: rgba(255,255,255,0.1); color: #fff; }\n"
"::-webkit-scrollbar { width: 5px; }\n"
"::-webkit-scrollbar-track { background: transparent; }\n"
"::-webkit-scrollbar-thumb { background: #2a2a2a; border-radius: 3px; }\n"
"\n"
".page { max-width: 720px; margin: 0 auto; padding: 32px 24px; }\n"
"\n"
"h1 { font-family: 'Inter', sans-serif; font-size: 32px; font-weight: 500; color: #e8e8e8; margin-bottom: 8px; }\n"
"h2 { font-family: 'Inter', sans-serif; font-size: 18px; font-weight: 500; color: #e8e8e8; margin-bottom: 16px; margin-top: 48px; }\n"
"p { font-size: 14.5px; color: #888888; line-height: 1.7; margin-bottom: 16px; }\n"
".claim { font-size: 15px; color: #888888; line-height: 1.6; margin-bottom: 20px; }\n"
"\n"
".metric-card {\n"
"  background: #1a1a1a; border: 1px solid #2a2a2a; border-radius: 8px;\n"
"  padding: 16px; display: inline-block; margin-bottom: 20px;\n"
"}\n"
".metric-value { font-family: 'JetBrains Mono', monospace; font-size: 28px; color: #e8e8e8; }\n"
".metric-label { font-family: 'Inter', sans-serif; font-size: 12px; color: #666666; margin-top: 4px; }\n"
"\n"
".badge-row { margin-bottom: 32px; }\n"
".badge {\n"
"  display: inline-block; background: #1e1e1e; border: 1px solid #333;\n"
"  border-radius: 4px; padding: 3px 10px; font-size: 12px;\n"
"  font-family: 'Inter', sans-serif; color: #888; margin-right: 6px; margin-bottom: 6px;\n"
"}\n"
"\n"
"/* RuneOS uses neutral surface, no accent color for callout */\n"
".callout {\n"
"  background: #141414; border-left: 3px solid #1e1e1e;\n"
"  border-radius: 0 8px 8px 0; padding: 16px 20px; margin: 24px 0;\n"
"}\n"
".callout p { color: #888888; margin-bottom: 0; }\n"
".callout p + p { margin-top: 12px; }\n"
"\n"
"pre.diagram {\n"
"  font-family: 'JetBrains Mono', monospace; font-size: 13px;\n"
"  background: #141414; padding: 20px; border-radius: 8px;\n"
"  border: 1px solid #2a2a2a; overflow-x: auto; white-space: pre;\n"
"  color: #888; line-height: 1.5;\n"
"}\n"
"\n"
"/* --- SYSCALL TABLE --- */\n"
".syscall-table {\n"
"  font-family: 'JetBrains Mono', monospace; font-size: 13px;\n"
"  background: #1a1a1a; border: 1px solid #2a2a2a; border-radius: 8px;\n"
"  padding: 16px 20px; margin: 16px 0;\n"
"}\n"
".syscall-row {\n"
"  display: grid; grid-template-columns: 110px 36px 1fr;\n"
"  gap: 0 12px; padding: 5px 0;\n"
"  border-bottom: 1px solid #1e1e1e;\n"
"}\n"
".syscall-row:last-child { border-bottom: none; }\n"
".syscall-name { color: #e8e8e8; }\n"
".syscall-num { color: #555; text-align: center; }\n"
".syscall-desc { color: #666; font-size: 12px; }\n"
"\n"
"/* --- VFS TREE --- */\n"
".vfs-block {\n"
"  font-family: 'JetBrains Mono', monospace; font-size: 13px;\n"
"  background: #1a1a1a; border: 1px solid #2a2a2a; border-radius: 8px;\n"
"  padding: 16px 20px; margin: 16px 0; white-space: pre; color: #888;\n"
"  line-height: 1.7; overflow-x: auto;\n"
"}\n"
".fn-ptr { color: #555; }\n"
"\n"
"/* --- METRICS ROW --- */\n"
".metrics-row {\n"
"  display: grid; grid-template-columns: repeat(5, 1fr);\n"
"  gap: 10px; margin: 24px 0;\n"
"}\n"
".metric-card-sm {\n"
"  background: #1a1a1a; border: 1px solid #2a2a2a; border-radius: 8px;\n"
"  padding: 14px 10px; text-align: center;\n"
"}\n"
".metric-card-sm .val {\n"
"  font-family: 'JetBrains Mono', monospace; font-size: 18px; color: #e8e8e8;\n"
"}\n"
".metric-card-sm .val.green { color: #22c55e; }\n"
".metric-card-sm .lbl {\n"
"  font-family: 'Inter', sans-serif; font-size: 11px; color: #666;\n"
"  margin-top: 4px; text-transform: uppercase; letter-spacing: 0.5px;\n"
"}\n"
"\n"
".tech-stack { margin: 32px 0; }\n"
".pill {\n"
"  display: inline-block; background: #1e1e1e; border: 1px solid #333;\n"
"  border-radius: 4px; padding: 3px 10px; font-size: 12px;\n"
"  font-family: 'Inter', sans-serif; color: #888; margin-right: 6px; margin-bottom: 6px;\n"
"}\n"
"\n"
".retro { margin-top: 48px; }\n"
".retro h2 { font-size: 14px; color: #555; text-transform: uppercase; letter-spacing: 1.5px; }\n"
".retro ul { list-style: none; padding: 0; }\n"
".retro li {\n"
"  font-size: 13.5px; color: #666; padding: 6px 0 6px 16px; position: relative; line-height: 1.5;\n"
"}\n"
".retro li::before { content: \"—\"; position: absolute; left: 0; color: #444; }\n"
"\n"
".section-divider { border: none; border-top: 1px solid #1a1a1a; margin: 48px 0; }\n"
"\n"
"@media (max-width: 600px) {\n"
"  .metrics-row { grid-template-columns: repeat(3, 1fr); }\n"
"  .syscall-row { grid-template-columns: 90px 30px 1fr; font-size: 11px; }\n"
"  pre.diagram { font-size: 10px; }\n"
"}\n"
"@media (max-width: 420px) {\n"
"  .metrics-row { grid-template-columns: repeat(2, 1fr); }\n"
"}\n"
"</style>\n"
"</head>\n"
"<body>\n"
"<div class=\"page\">\n"
"\n"
"  <!-- LAYER 1 — Above the fold -->\n"
"  <h1>RuneOS v2.0</h1>\n"
"  <p class=\"claim\">A portfolio that boots — 31 KB of C compiled to WebAssembly, with a real process scheduler, virtual filesystem, and 9 syscalls running in your browser right now</p>\n"
"\n"
"  <div class=\"metric-card\">\n"
"    <div class=\"metric-value\">31 KB</div>\n"
"    <div class=\"metric-label\">total WASM binary</div>\n"
"  </div>\n"
"\n"
"  <p>Most portfolios are React apps or templates. This one has a process table, a syscall dispatch handler, and a virtual filesystem — compiled from C to WebAssembly via Emscripten. Every command you type in the terminal runs through actual C code. You are reading this document inside the thing it describes.</p>\n"
"\n"
"  <div class=\"badge-row\">\n"
"    <span class=\"badge\">C → WebAssembly</span>\n"
"    <span class=\"badge\">Emscripten</span>\n"
"    <span class=\"badge\">Zero dependencies</span>\n"
"    <span class=\"badge\">Vanilla JS</span>\n"
"  </div>\n"
"\n"
"  <hr class=\"section-divider\">\n"
"\n"
"  <!-- LAYER 2 — Why C -->\n"
"  <h2>Why C instead of JavaScript</h2>\n"
"\n"
"  <div class=\"callout\">\n"
"    <p>JavaScript was the obvious choice. C was the interesting one. WebAssembly gave a real compilation target — which meant deliberate memory layout decisions, a real build pipeline, and a binary that is fully self-contained. The kernel has no malloc from libc; memory tracking is manual against a 64 KB virtual budget. The output from every command is captured via a 4 KB ring buffer (buf_printf) instead of stdout — Emscripten's printf redirection was bypassed for performance. The constraint made the engineering more honest. A 31 KB binary with a working scheduler is a better portfolio piece than a Create React App template.</p>\n"
"  </div>\n"
"\n"
"  <hr class=\"section-divider\">\n"
"\n"
"  <!-- LAYER 3 — Architecture -->\n"
"  <h2>Architecture</h2>\n"
"\n"
"<pre class=\"diagram\">\n"
"┌─────────────────────────────────────────────────────────┐\n"
"│                    BROWSER RUNTIME                      │\n"
"│                                                         │\n"
"│  ┌─────────────────────────────────────────────────┐   │\n"
"│  │              PRESENTATION LAYER                  │   │\n"
"│  │  webpage.html · index.css · Fonts / Icons        │   │\n"
"│  └────────────────────┬────────────────────────────┘   │\n"
"│                       │                                 │\n"
"│  ┌────────────────────┴────────────────────────────┐   │\n"
"│  │          APPLICATION LAYER (Vanilla JS)          │   │\n"
"│  │  main.js        entry, WASM bridge, events       │   │\n"
"│  │  System.js      boot, clock, kernel poll (3s)    │   │\n"
"│  │  WindowManager  drag, maximize, minimize         │   │\n"
"│  │  AppManager     lifecycle, 6 render types        │   │\n"
"│  └────────────────────┬────────────────────────────┘   │\n"
"│                       │  cwrap() / ccall()              │\n"
"│  ┌────────────────────┴────────────────────────────┐   │\n"
"│  │        KERNEL LAYER (C → WASM, ~31 KB)           │   │\n"
"│  │  kernel_wasm.c   3 exports, 4 KB ring buffer     │   │\n"
"│  │  core/kernel.c   9 syscalls, 32-slot proc table  │   │\n"
"│  │  core/vfs.c      tree + fn pointer virtual files │   │\n"
"│  │  core/resume.c   embedded HTML resume            │   │\n"
"│  └─────────────────────────────────────────────────┘   │\n"
"│                                                         │\n"
"└─────────────────────────────────────────────────────────┘\n"
"</pre>\n"
"\n"
"  <h2>Syscall Table</h2>\n"
"  <div class=\"syscall-table\">\n"
"    <div class=\"syscall-row\"><span class=\"syscall-name\">SYS_PING</span><span class=\"syscall-num\">(0)</span><span class=\"syscall-desc\">health check → \"pong\"</span></div>\n"
"    <div class=\"syscall-row\"><span class=\"syscall-name\">SYS_SPAWN</span><span class=\"syscall-num\">(1)</span><span class=\"syscall-desc\">create process, return PID</span></div>\n"
"    <div class=\"syscall-row\"><span class=\"syscall-name\">SYS_EXIT</span><span class=\"syscall-num\">(2)</span><span class=\"syscall-desc\">terminate process</span></div>\n"
"    <div class=\"syscall-row\"><span class=\"syscall-name\">SYS_REAP</span><span class=\"syscall-num\">(3)</span><span class=\"syscall-desc\">reclaim dead slot (init only)</span></div>\n"
"    <div class=\"syscall-row\"><span class=\"syscall-name\">SYS_READ</span><span class=\"syscall-num\">(4)</span><span class=\"syscall-desc\">read file from VFS path</span></div>\n"
"    <div class=\"syscall-row\"><span class=\"syscall-name\">SYS_WRITE</span><span class=\"syscall-num\">(5)</span><span class=\"syscall-desc\">write to VFS file</span></div>\n"
"    <div class=\"syscall-row\"><span class=\"syscall-name\">SYS_MKDIR</span><span class=\"syscall-num\">(6)</span><span class=\"syscall-desc\">create directory</span></div>\n"
"    <div class=\"syscall-row\"><span class=\"syscall-name\">SYS_LS</span><span class=\"syscall-num\">(7)</span><span class=\"syscall-desc\">list directory contents</span></div>\n"
"    <div class=\"syscall-row\"><span class=\"syscall-name\">SYS_TOUCH</span><span class=\"syscall-num\">(8)</span><span class=\"syscall-desc\">create empty file</span></div>\n"
"  </div>\n"
"\n"
"  <h2>Virtual Filesystem</h2>\n"
"  <div class=\"vfs-block\">/\n"
"├── proc/\n"
"│   └── ps          <span class=\"fn-ptr\">→ proc_ps_read()   (computed live)</span>\n"
"├── kernel/\n"
"│   └── state       <span class=\"fn-ptr\">→ kernel_state_read()</span>\n"
"├── ai/\n"
"│   └── input       <span class=\"fn-ptr\">→ ai_input_write()</span>\n"
"└── home/           <span class=\"fn-ptr\">(user-writable)</span>\n"
"    ├── resume.txt\n"
"    └── projects/</div>\n"
"\n"
"  <div class=\"metrics-row\">\n"
"    <div class=\"metric-card-sm\"><div class=\"val\">~31 KB</div><div class=\"lbl\">Binary</div></div>\n"
"    <div class=\"metric-card-sm\"><div class=\"val\">9</div><div class=\"lbl\">Syscalls</div></div>\n"
"    <div class=\"metric-card-sm\"><div class=\"val\">32</div><div class=\"lbl\">Max Procs</div></div>\n"
"    <div class=\"metric-card-sm\"><div class=\"val green\">None</div><div class=\"lbl\">Backend</div></div>\n"
"    <div class=\"metric-card-sm\"><div class=\"val green\">Zero</div><div class=\"lbl\">Dependencies</div></div>\n"
"  </div>\n"
"\n"
"  <div class=\"tech-stack\">\n"
"    <span class=\"pill\">C</span>\n"
"    <span class=\"pill\">Emscripten</span>\n"
"    <span class=\"pill\">WebAssembly</span>\n"
"    <span class=\"pill\">Vanilla JS</span>\n"
"    <span class=\"pill\">HTML/CSS</span>\n"
"  </div>\n"
"\n"
"  <hr class=\"section-divider\">\n"
"\n"
"  <!-- BOTTOM — Retrospective -->\n"
"  <div class=\"retro\">\n"
"    <h2>What I'd do differently</h2>\n"
"    <ul>\n"
"      <li>The MMU tracks a 64 KB virtual budget but doesn't enforce real memory isolation — actual isolation would require WASM memory segment manipulation that Emscripten doesn't expose</li>\n"
"      <li>Content is baked into the binary at compile time — changing the resume means recompiling. A smarter VFS would lazy-load from a static JSON file</li>\n"
"      <li>The 4 KB ring buffer in wasm_run_command is a hard truncation limit — commands generating more than 4 KB of output silently cut off</li>\n"
"      <li>Window manager not optimized for many simultaneous windows</li>\n"
"    </ul>\n"
"  </div>\n"
"\n"
"</div>\n"
"</body>\n"
"</html>\n"
;

const char *get_project_runeos_html(void) {
    return project_runeos_html;
}

