/* project_gem.c — Project HTML embedded in the kernel */

const char *project_gem_html =
"<!-- FILE: projects/gem/index.html -->\n"
"<!DOCTYPE html>\n"
"<html lang=\"en\">\n"
"<head>\n"
"<meta charset=\"UTF-8\">\n"
"<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
"<title>GEM — AI Agent</title>\n"
"<style>\n"
"*, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }\n"
"body {\n"
"  font-family: 'Inter', system-ui, sans-serif;\n"
"  background: #0d0d0d;\n"
"  color: #e8e8e8;\n"
"  line-height: 1.65;\n"
"  overflow-y: auto;\n"
"  -webkit-font-smoothing: antialiased;\n"
"}\n"
"::selection { background: rgba(255,255,255,0.1); color: #fff; }\n"
"::-webkit-scrollbar { width: 5px; }\n"
"::-webkit-scrollbar-track { background: transparent; }\n"
"::-webkit-scrollbar-thumb { background: #2a2a2a; border-radius: 3px; }\n"
"\n"
".page { max-width: 720px; margin: 0 auto; padding: 32px 24px; }\n"
"\n"
"h1 { font-family: 'Inter', sans-serif; font-size: 32px; font-weight: 500; color: #e8e8e8; margin-bottom: 8px; }\n"
"h2 { font-family: 'Inter', sans-serif; font-size: 18px; font-weight: 500; color: #e8e8e8; margin-bottom: 16px; margin-top: 48px; }\n"
"p { font-size: 14.5px; color: #888888; line-height: 1.7; margin-bottom: 16px; }\n"
".claim { font-size: 15px; color: #888888; line-height: 1.6; margin-bottom: 20px; }\n"
"\n"
".metric-card {\n"
"  background: #1a1a1a; border: 1px solid #2a2a2a; border-radius: 8px;\n"
"  padding: 16px; display: inline-block; margin-bottom: 20px;\n"
"}\n"
".metric-value { font-family: 'JetBrains Mono', monospace; font-size: 28px; color: #e8e8e8; }\n"
".metric-label { font-family: 'Inter', sans-serif; font-size: 12px; color: #666666; margin-top: 4px; }\n"
"\n"
".badge-row { margin-bottom: 32px; }\n"
".badge {\n"
"  display: inline-block; background: #1e1e1e; border: 1px solid #333;\n"
"  border-radius: 4px; padding: 3px 10px; font-size: 12px;\n"
"  font-family: 'Inter', sans-serif; color: #888; margin-right: 6px; margin-bottom: 6px;\n"
"}\n"
"\n"
".callout {\n"
"  background: #141414; border-left: 3px solid #22c55e;\n"
"  border-radius: 0 8px 8px 0; padding: 16px 20px; margin: 24px 0;\n"
"}\n"
".callout p { color: #888888; margin-bottom: 0; }\n"
".callout p + p { margin-top: 12px; }\n"
"\n"
".video-placeholder {\n"
"  background: #1a1a1a; border: 1px dashed #333; border-radius: 16px;\n"
"  padding: 56px 24px; text-align: center; margin: 24px 0;\n"
"}\n"
".video-placeholder .label { font-family: 'Inter', sans-serif; font-size: 14px; color: #555; }\n"
"\n"
".pipeline-step {\n"
"  background: #1a1a1a; border: 1px solid #2a2a2a; border-radius: 6px;\n"
"  padding: 8px 14px; font-family: 'JetBrains Mono', monospace; font-size: 13px;\n"
"  color: #e8e8e8; text-align: center;\n"
"}\n"
".pipeline-arrow { text-align: center; color: #444; font-size: 14px; padding: 4px 0; }\n"
".pipeline-label {\n"
"  font-family: 'Inter', sans-serif; font-size: 12px; color: #555;\n"
"  text-align: center; margin-bottom: 8px;\n"
"}\n"
"\n"
".tool-chip {\n"
"  display: inline-block; background: #1a1a1a; border: 1px solid #2a2a2a;\n"
"  border-radius: 4px; padding: 4px 12px;\n"
"  font-family: 'JetBrains Mono', monospace; font-size: 12px;\n"
"  color: #888; margin: 3px;\n"
"}\n"
"\n"
".tool-row { text-align: center; margin: 8px 0; }\n"
"\n"
".highlight { margin-bottom: 24px; }\n"
".highlight-title { font-family: 'Inter', sans-serif; font-size: 14px; font-weight: 500; color: #e8e8e8; margin-bottom: 6px; }\n"
".highlight p { font-size: 13.5px; color: #888; }\n"
"\n"
".tech-stack { margin: 32px 0; }\n"
".pill {\n"
"  display: inline-block; background: #1e1e1e; border: 1px solid #333;\n"
"  border-radius: 4px; padding: 3px 10px; font-size: 12px;\n"
"  font-family: 'Inter', sans-serif; color: #888; margin-right: 6px; margin-bottom: 6px;\n"
"}\n"
"\n"
".limitations { margin-top: 48px; }\n"
".limitations h2 { font-size: 14px; color: #555; text-transform: uppercase; letter-spacing: 1.5px; }\n"
".limitations ul { list-style: none; padding: 0; }\n"
".limitations li {\n"
"  font-size: 13.5px; color: #666; padding: 6px 0 6px 16px; position: relative; line-height: 1.5;\n"
"}\n"
".limitations li::before { content: \"—\"; position: absolute; left: 0; color: #444; }\n"
"\n"
".section-divider { border: none; border-top: 1px solid #1a1a1a; margin: 48px 0; }\n"
"</style>\n"
"</head>\n"
"<body>\n"
"<div class=\"page\">\n"
"\n"
"  <!-- LAYER 1 — Above the fold -->\n"
"  <h1>GEM</h1>\n"
"  <p class=\"claim\">A RAG-grounded agent that searches the web, writes code, runs it on your machine, and speaks the result — built before agent frameworks existed</p>\n"
"\n"
"  <div class=\"metric-card\">\n"
"    <div class=\"metric-value\">5 live tools</div>\n"
"    <div class=\"metric-label\">web, shell, code, notes, files</div>\n"
"  </div>\n"
"\n"
"  <p>GEM is a personal AI assistant that goes beyond chat. It retrieves live information from multiple sources, reasons about which tool to use, executes that tool on your local machine, and returns a grounded answer. Built when most LLM wrappers were still stateless chatbots. The interesting part was building the tool-use dispatch loop before LangChain normalized the pattern.</p>\n"
"\n"
"  <div class=\"badge-row\">\n"
"    <span class=\"badge\">AI Agent</span>\n"
"    <span class=\"badge\">RAG</span>\n"
"    <span class=\"badge\">Tool Use</span>\n"
"    <span class=\"badge\">Voice I/O</span>\n"
"  </div>\n"
"\n"
"  <hr class=\"section-divider\">\n"
"\n"
"  <!-- LAYER 2 — The Loop -->\n"
"  <h2>The loop</h2>\n"
"\n"
"  <div class=\"callout\">\n"
"    <p>The failure mode of a naive LLM assistant is hallucination — it confidently invents file paths, command flags, and API responses. RAG is the fix: before the LLM reasons, relevant context is retrieved from real sources and injected into the prompt. The LLM then decides whether to answer directly or call a tool. If it calls a tool, the result comes back into the loop as new context. The answer is always grounded in something that actually happened.</p>\n"
"  </div>\n"
"\n"
"  <div style=\"margin: 32px 0;\">\n"
"    <div class=\"pipeline-step\">User query (voice or text)</div>\n"
"    <div class=\"pipeline-arrow\">↓</div>\n"
"    <div class=\"pipeline-step\">Retrieval layer</div>\n"
"    <div class=\"tool-row\">\n"
"      <span class=\"tool-chip\">Wikipedia</span>\n"
"      <span class=\"tool-chip\">SearxNG</span>\n"
"      <span class=\"tool-chip\">NewsAPI</span>\n"
"      <span class=\"tool-chip\">Semantic Scholar</span>\n"
"      <span class=\"tool-chip\">Haystack</span>\n"
"    </div>\n"
"    <div class=\"pipeline-arrow\">↓</div>\n"
"    <div class=\"pipeline-step\">LLM reasoning — answer directly, or call a tool?</div>\n"
"    <div class=\"pipeline-arrow\">↓</div>\n"
"    <div class=\"pipeline-step\">Tool dispatch</div>\n"
"    <div class=\"tool-row\">\n"
"      <span class=\"tool-chip\">shell_cmd</span>\n"
"      <span class=\"tool-chip\">write_code</span>\n"
"      <span class=\"tool-chip\">run_code</span>\n"
"      <span class=\"tool-chip\">notes</span>\n"
"      <span class=\"tool-chip\">web_search</span>\n"
"    </div>\n"
"    <div class=\"pipeline-arrow\">↓</div>\n"
"    <div class=\"pipeline-step\">Local execution</div>\n"
"    <div class=\"pipeline-arrow\">↓</div>\n"
"    <div class=\"pipeline-step\">Result → spoken + text response</div>\n"
"  </div>\n"
"\n"
"  <div class=\"video-placeholder\">\n"
"    <span class=\"material-symbols-rounded\" style=\"font-size:48px;color:#444;display:block;margin-bottom:12px\">play_circle</span>\n"
"    <span class=\"label\">Demo video coming soon</span>\n"
"  </div>\n"
"\n"
"  <hr class=\"section-divider\">\n"
"\n"
"  <!-- LAYER 3 — Technical Highlights -->\n"
"  <h2>Technical Highlights</h2>\n"
"\n"
"  <div class=\"highlight\">\n"
"    <div class=\"highlight-title\">1. Custom tool-use routing before frameworks existed</div>\n"
"    <p>The dispatch logic — deciding which tool to call and with what arguments — was built from scratch. LangChain's tool-use abstraction didn't exist in this form yet.</p>\n"
"  </div>\n"
"\n"
"  <div class=\"highlight\">\n"
"    <div class=\"highlight-title\">2. RAG as a safety layer</div>\n"
"    <p>Without retrieval grounding, the LLM would hallucinate shell commands. The retrieval step is not just for information — it's what makes local execution safe.</p>\n"
"  </div>\n"
"\n"
"  <div class=\"highlight\">\n"
"    <div class=\"highlight-title\">3. Voice pipeline latency</div>\n"
"    <p>The round-trip speech→STT→retrieval→LLM→TTS→speaker has to feel responsive. Each stage was optimized independently to keep total latency under 3s.</p>\n"
"  </div>\n"
"\n"
"  <div class=\"tech-stack\">\n"
"    <span class=\"pill\">Python</span>\n"
"    <span class=\"pill\">RAG</span>\n"
"    <span class=\"pill\">Haystack</span>\n"
"    <span class=\"pill\">SearxNG</span>\n"
"    <span class=\"pill\">Wikipedia API</span>\n"
"    <span class=\"pill\">NewsAPI</span>\n"
"    <span class=\"pill\">Semantic Scholar</span>\n"
"    <span class=\"pill\">Voice I/O</span>\n"
"  </div>\n"
"\n"
"  <hr class=\"section-divider\">\n"
"\n"
"  <!-- BOTTOM — Limitations -->\n"
"  <div class=\"limitations\">\n"
"    <h2>Limitations</h2>\n"
"    <ul>\n"
"      <li>No persistent memory across sessions</li>\n"
"      <li>Tool execution is sequential, not parallel</li>\n"
"      <li>No execution sandboxing — trust is assumed</li>\n"
"      <li>Single user only</li>\n"
"    </ul>\n"
"  </div>\n"
"\n"
"</div>\n"
"</body>\n"
"</html>\n"
;

const char *get_project_gem_html(void) {
    return project_gem_html;
}

