/* project_arecanut.c — Project HTML embedded in the kernel */

const char *project_arecanut_html =
"<!-- FILE: projects/arecanut/index.html -->\n"
"<!DOCTYPE html>\n"
"<html lang=\"en\">\n"
"<head>\n"
"<meta charset=\"UTF-8\">\n"
"<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
"<title>Arecanut Disease Detector</title>\n"
"<style>\n"
"*, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }\n"
"body {\n"
"  font-family: 'Inter', system-ui, sans-serif;\n"
"  background: #0d0d0d;\n"
"  color: #e8e8e8;\n"
"  line-height: 1.65;\n"
"  overflow-y: auto;\n"
"  -webkit-font-smoothing: antialiased;\n"
"}\n"
"::selection { background: rgba(255,255,255,0.1); color: #fff; }\n"
"::-webkit-scrollbar { width: 5px; }\n"
"::-webkit-scrollbar-track { background: transparent; }\n"
"::-webkit-scrollbar-thumb { background: #2a2a2a; border-radius: 3px; }\n"
"\n"
".page { max-width: 720px; margin: 0 auto; padding: 32px 24px; }\n"
"\n"
"/* --- TYPOGRAPHY --- */\n"
"h1 { font-family: 'Inter', sans-serif; font-size: 32px; font-weight: 500; color: #e8e8e8; margin-bottom: 8px; }\n"
"h2 { font-family: 'Inter', sans-serif; font-size: 18px; font-weight: 500; color: #e8e8e8; margin-bottom: 16px; margin-top: 48px; }\n"
"p { font-size: 14.5px; color: #888888; line-height: 1.7; margin-bottom: 16px; }\n"
".claim { font-size: 15px; color: #888888; line-height: 1.6; margin-bottom: 20px; }\n"
"\n"
"/* --- METRIC CARD --- */\n"
".metric-card {\n"
"  background: #1a1a1a; border: 1px solid #2a2a2a; border-radius: 8px;\n"
"  padding: 16px; display: inline-block; margin-bottom: 20px;\n"
"}\n"
".metric-value { font-family: 'JetBrains Mono', monospace; font-size: 28px; color: #e8e8e8; }\n"
".metric-label { font-family: 'Inter', sans-serif; font-size: 12px; color: #666666; margin-top: 4px; }\n"
"\n"
"/* --- BADGE --- */\n"
".badge-row { margin-bottom: 32px; }\n"
".badge {\n"
"  display: inline-block; background: #1e1e1e; border: 1px solid #333;\n"
"  border-radius: 4px; padding: 3px 10px; font-size: 12px;\n"
"  font-family: 'Inter', sans-serif; color: #888; margin-right: 6px; margin-bottom: 6px;\n"
"}\n"
"\n"
"/* --- CALLOUT BOX --- */\n"
".callout {\n"
"  background: #141414; border-left: 3px solid #f59e0b;\n"
"  border-radius: 0 8px 8px 0; padding: 16px 20px; margin: 24px 0;\n"
"}\n"
".callout p { color: #888888; margin-bottom: 0; }\n"
".callout p + p { margin-top: 12px; }\n"
"\n"
"/* --- VIDEO PLACEHOLDER --- */\n"
".video-placeholder {\n"
"  background: #1a1a1a; border: 1px dashed #333; border-radius: 16px;\n"
"  padding: 56px 24px; text-align: center; margin: 24px 0;\n"
"}\n"
".video-placeholder .label { font-family: 'Inter', sans-serif; font-size: 14px; color: #555; }\n"
"\n"
"/* --- PIPELINE --- */\n"
".pipeline { margin: 24px 0; }\n"
".pipeline-columns { display: grid; grid-template-columns: 1fr 1fr; gap: 24px; }\n"
".pipeline-col-label {\n"
"  font-family: 'JetBrains Mono', monospace; font-size: 12px; color: #666;\n"
"  text-transform: uppercase; letter-spacing: 1px; margin-bottom: 12px; text-align: center;\n"
"}\n"
".pipeline-step {\n"
"  background: #1a1a1a; border: 1px solid #2a2a2a; border-radius: 6px;\n"
"  padding: 8px 14px; font-family: 'JetBrains Mono', monospace; font-size: 13px;\n"
"  color: #e8e8e8; text-align: center;\n"
"}\n"
".pipeline-arrow { text-align: center; color: #444; font-size: 14px; padding: 4px 0; }\n"
"\n"
"/* --- PRE DIAGRAM --- */\n"
"pre.diagram {\n"
"  font-family: 'JetBrains Mono', monospace; font-size: 13px;\n"
"  background: #141414; padding: 20px; border-radius: 8px;\n"
"  border: 1px solid #2a2a2a; overflow-x: auto; white-space: pre;\n"
"  color: #888; line-height: 1.5;\n"
"}\n"
"\n"
"/* --- TECH HIGHLIGHTS --- */\n"
".highlight { margin-bottom: 24px; }\n"
".highlight-title { font-family: 'Inter', sans-serif; font-size: 14px; font-weight: 500; color: #e8e8e8; margin-bottom: 6px; }\n"
".highlight p { font-size: 13.5px; color: #888; }\n"
"\n"
"/* --- TECH STACK --- */\n"
".tech-stack { margin: 32px 0; }\n"
".pill {\n"
"  display: inline-block; background: #1e1e1e; border: 1px solid #333;\n"
"  border-radius: 4px; padding: 3px 10px; font-size: 12px;\n"
"  font-family: 'Inter', sans-serif; color: #888; margin-right: 6px; margin-bottom: 6px;\n"
"}\n"
"\n"
"/* --- TABLE --- */\n"
".class-table { width: 100%; border-collapse: collapse; margin: 16px 0; }\n"
".class-table td {\n"
"  font-family: 'Inter', sans-serif; font-size: 13px; color: #888;\n"
"  padding: 5px 12px; border-bottom: 1px solid #1a1a1a;\n"
"}\n"
".class-table td:first-child { color: #e8e8e8; width: 50%; }\n"
"\n"
"/* --- LIMITATIONS --- */\n"
".limitations { margin-top: 48px; }\n"
".limitations h2 { font-size: 14px; color: #555; text-transform: uppercase; letter-spacing: 1.5px; }\n"
".limitations ul { list-style: none; padding: 0; }\n"
".limitations li {\n"
"  font-size: 13.5px; color: #666; padding: 6px 0 6px 16px; position: relative; line-height: 1.5;\n"
"}\n"
".limitations li::before { content: \"—\"; position: absolute; left: 0; color: #444; }\n"
"\n"
".section-divider { border: none; border-top: 1px solid #1a1a1a; margin: 48px 0; }\n"
"</style>\n"
"</head>\n"
"<body>\n"
"<div class=\"page\">\n"
"\n"
"  <!-- LAYER 1 — Above the fold -->\n"
"  <h1>Arecanut Disease Detector</h1>\n"
"  <p class=\"claim\">99.95% accuracy — validated on a test set with a completely different viewpoint distribution than training</p>\n"
"\n"
"  <div class=\"metric-card\">\n"
"    <div class=\"metric-value\">99.95%</div>\n"
"    <div class=\"metric-label\">accuracy</div>\n"
"  </div>\n"
"\n"
"  <p>Arecanut is Karnataka's primary cash crop. Farmers lose significant yield to diseases that are invisible until advanced. This system detects them from a phone photo or a drone survey — on-device, offline, no server. The interesting engineering was not getting high accuracy — it was proving the accuracy was real.</p>\n"
"\n"
"  <div class=\"badge-row\">\n"
"    <span class=\"badge\">Research Paper</span>\n"
"    <span class=\"badge\">Computer Vision</span>\n"
"    <span class=\"badge\">React Native</span>\n"
"    <span class=\"badge\">TFLite</span>\n"
"  </div>\n"
"\n"
"  <hr class=\"section-divider\">\n"
"\n"
"  <!-- LAYER 2 — Second screenful -->\n"
"  <h2>Why the accuracy number actually means something</h2>\n"
"\n"
"  <div class=\"callout\">\n"
"    <p>Most models trained on ground-level photos collapse when tested on drone footage — the viewpoint, scale, lighting, and angle are fundamentally different. This model was evaluated on a separate external dataset with a different distribution from training. Accuracy held at 99.95%.</p>\n"
"    <p>To verify the distributions were actually different (not just relabeled copies), MobileNetV2 embeddings were extracted from both sets and compared using cosine similarity and t-SNE visualization. The feature spaces were genuinely different. That makes the result meaningful.</p>\n"
"  </div>\n"
"\n"
"  <div class=\"video-placeholder\">\n"
"    <span class=\"material-symbols-rounded\" style=\"font-size:48px;color:#444;display:block;margin-bottom:12px\">play_circle</span>\n"
"    <span class=\"label\">Demo video coming soon</span>\n"
"  </div>\n"
"\n"
"  <hr class=\"section-divider\">\n"
"\n"
"  <!-- LAYER 3 — Architecture / Pipeline -->\n"
"  <h2>Pipeline</h2>\n"
"\n"
"  <div class=\"pipeline\">\n"
"    <div class=\"pipeline-columns\">\n"
"      <div>\n"
"        <div class=\"pipeline-col-label\">Mobile</div>\n"
"        <div class=\"pipeline-step\">Camera / Gallery</div>\n"
"        <div class=\"pipeline-arrow\">↓</div>\n"
"        <div class=\"pipeline-step\">Skia RGBA decode</div>\n"
"        <div class=\"pipeline-arrow\">↓</div>\n"
"        <div class=\"pipeline-step\">Manual BGR conversion</div>\n"
"        <div class=\"pipeline-arrow\">↓</div>\n"
"        <div class=\"pipeline-step\">224×224 Float32 tensor</div>\n"
"        <div class=\"pipeline-arrow\">↓</div>\n"
"        <div class=\"pipeline-step\">INT8 TFLite on-device</div>\n"
"        <div class=\"pipeline-arrow\">↓</div>\n"
"        <div class=\"pipeline-step\">9-class prediction</div>\n"
"        <div class=\"pipeline-arrow\">↓</div>\n"
"        <div class=\"pipeline-step\">Result + treatment card</div>\n"
"      </div>\n"
"      <div>\n"
"        <div class=\"pipeline-col-label\">Drone / UAV</div>\n"
"        <div class=\"pipeline-step\">GeoTIFF orthomosaic</div>\n"
"        <div class=\"pipeline-arrow\">↓</div>\n"
"        <div class=\"pipeline-step\">Tile extraction (100×100px)</div>\n"
"        <div class=\"pipeline-arrow\">↓</div>\n"
"        <div class=\"pipeline-step\">Upscale to 224×224</div>\n"
"        <div class=\"pipeline-arrow\">↓</div>\n"
"        <div class=\"pipeline-step\">CNN inference per tile</div>\n"
"        <div class=\"pipeline-arrow\">↓</div>\n"
"        <div class=\"pipeline-step\">Gaussian smoothing (SciPy)</div>\n"
"        <div class=\"pipeline-arrow\">↓</div>\n"
"        <div class=\"pipeline-step\">Disease density heatmap</div>\n"
"        <div class=\"pipeline-arrow\">↓</div>\n"
"        <div class=\"pipeline-step\">Overlay on aerial image</div>\n"
"      </div>\n"
"    </div>\n"
"  </div>\n"
"\n"
"  <h2>Technical Highlights</h2>\n"
"\n"
"  <div class=\"highlight\">\n"
"    <div class=\"highlight-title\">1. The RGBA→BGR problem</div>\n"
"    <p>React Native gives RGBA from camera. The Python training pipeline used OpenCV which reads BGR. Feeding RGBA into a BGR-trained model gives wrong predictions even when the image looks identical. Fix: read raw pixels from a Skia surface and manually reorder channels before building the Float32Array. Small detail, real consequence — without this the model would be unusable on mobile.</p>\n"
"  </div>\n"
"\n"
"  <div class=\"highlight\">\n"
"    <div class=\"highlight-title\">2. Domain shift validation</div>\n"
"    <p>Used MobileNetV2 + t-SNE + cosine similarity to confirm the external test set was genuinely out-of-distribution — not just a different split of the same photos.</p>\n"
"  </div>\n"
"\n"
"  <div class=\"highlight\">\n"
"    <div class=\"highlight-title\">3. INT8 quantization</div>\n"
"    <p>Full Keras H5 → TFLite INT8. Model is ~3MB, runs entirely on-device, no internet required.</p>\n"
"  </div>\n"
"\n"
"  <div class=\"tech-stack\">\n"
"    <span class=\"pill\">TensorFlow/Keras</span>\n"
"    <span class=\"pill\">TFLite INT8</span>\n"
"    <span class=\"pill\">React Native</span>\n"
"    <span class=\"pill\">Expo SDK 54</span>\n"
"    <span class=\"pill\">TypeScript</span>\n"
"    <span class=\"pill\">Skia</span>\n"
"    <span class=\"pill\">react-native-fast-tflite</span>\n"
"    <span class=\"pill\">Rasterio</span>\n"
"    <span class=\"pill\">SciPy</span>\n"
"    <span class=\"pill\">Python</span>\n"
"    <span class=\"pill\">Matplotlib</span>\n"
"  </div>\n"
"\n"
"  <h2>9 Classes</h2>\n"
"  <table class=\"class-table\">\n"
"    <tr><td>Mahali Koleroga</td><td>Disease</td></tr>\n"
"    <tr><td>Stem Bleeding</td><td>Disease</td></tr>\n"
"    <tr><td>Bud Borer</td><td>Disease</td></tr>\n"
"    <tr><td>Stem Cracking</td><td>Disease</td></tr>\n"
"    <tr><td>Yellow Leaf Disease</td><td>Disease</td></tr>\n"
"    <tr><td>Healthy Leaf</td><td>Healthy</td></tr>\n"
"    <tr><td>Healthy Nut</td><td>Healthy</td></tr>\n"
"    <tr><td>Healthy Trunk</td><td>Healthy</td></tr>\n"
"    <tr><td>Healthy Foot</td><td>Healthy</td></tr>\n"
"  </table>\n"
"\n"
"  <hr class=\"section-divider\">\n"
"\n"
"  <!-- BOTTOM — Limitations -->\n"
"  <div class=\"limitations\">\n"
"    <h2>Limitations</h2>\n"
"    <ul>\n"
"      <li>Limited to 9 trained classes — novel diseases not recognized</li>\n"
"      <li>Drone pipeline tested at one altitude range</li>\n"
"      <li>Chatbot is keyword-matching only, not semantic</li>\n"
"      <li>iOS build untested (Android primary)</li>\n"
"      <li>Real-time video inference not implemented</li>\n"
"    </ul>\n"
"  </div>\n"
"\n"
"</div>\n"
"</body>\n"
"</html>\n"
;

const char *get_project_arecanut_html(void) {
    return project_arecanut_html;
}

