/* project_arshirt.c — Project HTML embedded in the kernel */

const char *project_arshirt_html =
"<!-- FILE: projects/arshirt/index.html -->\n"
"<!DOCTYPE html>\n"
"<html lang=\"en\">\n"
"<head>\n"
"<meta charset=\"UTF-8\">\n"
"<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
"<title>ARWear — Real-time AR Try-on</title>\n"
"<style>\n"
"*, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }\n"
"body {\n"
"  font-family: 'Inter', system-ui, sans-serif;\n"
"  background: #0d0d0d;\n"
"  color: #e8e8e8;\n"
"  line-height: 1.65;\n"
"  overflow-y: auto;\n"
"  -webkit-font-smoothing: antialiased;\n"
"}\n"
"::selection { background: rgba(255,255,255,0.1); color: #fff; }\n"
"::-webkit-scrollbar { width: 5px; }\n"
"::-webkit-scrollbar-track { background: transparent; }\n"
"::-webkit-scrollbar-thumb { background: #2a2a2a; border-radius: 3px; }\n"
"\n"
".page { max-width: 720px; margin: 0 auto; padding: 32px 24px; }\n"
"\n"
"h1 { font-family: 'Inter', sans-serif; font-size: 32px; font-weight: 500; color: #e8e8e8; margin-bottom: 8px; }\n"
"h2 { font-family: 'Inter', sans-serif; font-size: 18px; font-weight: 500; color: #e8e8e8; margin-bottom: 16px; margin-top: 48px; }\n"
"p { font-size: 14.5px; color: #888888; line-height: 1.7; margin-bottom: 16px; }\n"
".claim { font-size: 15px; color: #888888; line-height: 1.6; margin-bottom: 20px; }\n"
"\n"
".metric-card {\n"
"  background: #1a1a1a; border: 1px solid #2a2a2a; border-radius: 8px;\n"
"  padding: 16px; display: inline-block; margin-bottom: 20px;\n"
"}\n"
".metric-value { font-family: 'JetBrains Mono', monospace; font-size: 28px; color: #e8e8e8; }\n"
".metric-label { font-family: 'Inter', sans-serif; font-size: 12px; color: #666666; margin-top: 4px; }\n"
"\n"
".badge-row { margin-bottom: 32px; }\n"
".badge {\n"
"  display: inline-block; background: #1e1e1e; border: 1px solid #333;\n"
"  border-radius: 4px; padding: 3px 10px; font-size: 12px;\n"
"  font-family: 'Inter', sans-serif; color: #888; margin-right: 6px; margin-bottom: 6px;\n"
"}\n"
"\n"
".callout {\n"
"  background: #141414; border-left: 3px solid #a855f7;\n"
"  border-radius: 0 8px 8px 0; padding: 16px 20px; margin: 24px 0;\n"
"}\n"
".callout p { color: #888888; margin-bottom: 0; }\n"
".callout p + p { margin-top: 12px; }\n"
"\n"
".video-placeholder {\n"
"  background: #1a1a1a; border: 1px dashed #333; border-radius: 16px;\n"
"  padding: 56px 24px; text-align: center; margin: 24px 0;\n"
"}\n"
".video-placeholder.hero {\n"
"  padding: 80px 24px;\n"
"}\n"
".video-placeholder .label { font-family: 'Inter', sans-serif; font-size: 15px; color: #e8e8e8; }\n"
".video-placeholder .sublabel { font-family: 'Inter', sans-serif; font-size: 14px; color: #555; margin-top: 8px; }\n"
"\n"
".pipeline-horiz {\n"
"  display: flex; align-items: center; flex-wrap: wrap; gap: 0;\n"
"  margin: 24px 0; justify-content: center;\n"
"}\n"
".pipeline-step {\n"
"  background: #1a1a1a; border: 1px solid #2a2a2a; border-radius: 6px;\n"
"  padding: 8px 14px; font-family: 'JetBrains Mono', monospace; font-size: 12px;\n"
"  color: #e8e8e8; white-space: nowrap;\n"
"}\n"
".pipeline-arrow-h { color: #444; font-size: 14px; padding: 0 6px; }\n"
"\n"
".highlight { margin-bottom: 24px; }\n"
".highlight-title { font-family: 'Inter', sans-serif; font-size: 14px; font-weight: 500; color: #e8e8e8; margin-bottom: 6px; }\n"
".highlight p { font-size: 13.5px; color: #888; }\n"
"\n"
".tech-stack { margin: 32px 0; }\n"
".pill {\n"
"  display: inline-block; background: #1e1e1e; border: 1px solid #333;\n"
"  border-radius: 4px; padding: 3px 10px; font-size: 12px;\n"
"  font-family: 'Inter', sans-serif; color: #888; margin-right: 6px; margin-bottom: 6px;\n"
"}\n"
"\n"
".limitations { margin-top: 48px; }\n"
".limitations h2 { font-size: 14px; color: #555; text-transform: uppercase; letter-spacing: 1.5px; }\n"
".limitations ul { list-style: none; padding: 0; }\n"
".limitations li {\n"
"  font-size: 13.5px; color: #666; padding: 6px 0 6px 16px; position: relative; line-height: 1.5;\n"
"}\n"
".limitations li::before { content: \"—\"; position: absolute; left: 0; color: #444; }\n"
"\n"
".section-divider { border: none; border-top: 1px solid #1a1a1a; margin: 48px 0; }\n"
"</style>\n"
"</head>\n"
"<body>\n"
"<div class=\"page\">\n"
"\n"
"  <!-- LAYER 1 — Above the fold -->\n"
"  <h1>ARWear</h1>\n"
"  <p class=\"claim\">Real-time 3D garment try-on using 33 pose landmarks to drive a mesh with thousands of vertices — no depth sensor</p>\n"
"\n"
"  <div class=\"metric-card\">\n"
"    <div class=\"metric-value\">33 → ∞ vertices</div>\n"
"    <div class=\"metric-label\">&lt;33ms per frame</div>\n"
"  </div>\n"
"\n"
"  <p>Point a webcam at yourself and a 3D t-shirt appears on your body, moves when you move, rotates when you turn. No depth sensor, no markers, no special hardware. Just RGB video, MediaPipe pose estimation, and a mesh binding algorithm that maps 33 sparse skeleton points to a dense garment mesh in real time.</p>\n"
"\n"
"  <div class=\"badge-row\">\n"
"    <span class=\"badge\">Computer Vision</span>\n"
"    <span class=\"badge\">Real-time AR</span>\n"
"    <span class=\"badge\">MediaPipe</span>\n"
"    <span class=\"badge\">3D</span>\n"
"  </div>\n"
"\n"
"  <hr class=\"section-divider\">\n"
"\n"
"  <!-- LAYER 2 — Video-dominant + Story -->\n"
"  <div class=\"video-placeholder hero\">\n"
"    <span class=\"material-symbols-rounded\" style=\"font-size:56px;color:#444;display:block;margin-bottom:12px\">play_circle</span>\n"
"    <span class=\"label\">This project is best understood in motion</span>\n"
"    <div class=\"sublabel\">Demo video coming soon</div>\n"
"  </div>\n"
"\n"
"  <h2>The actual hard part</h2>\n"
"\n"
"  <div class=\"callout\">\n"
"    <p>Rendering a 3D model is a solved problem. The hard part is binding — for every vertex in a garment mesh, determining which skeleton joints influence it and by how much, so that when a shoulder rises, the fabric over it rises naturally without the collar warping or the sleeve tearing.</p>\n"
"    <p>MediaPipe gives you 33 keypoints. Getting smooth, stable, real-time deformation from 33 sparse inputs across thousands of mesh vertices — without jitter when you move fast, without drift when you hold still — is the problem.</p>\n"
"  </div>\n"
"\n"
"  <hr class=\"section-divider\">\n"
"\n"
"  <!-- LAYER 3 — Pipeline + Highlights -->\n"
"  <h2>Pipeline</h2>\n"
"\n"
"  <div class=\"pipeline-horiz\">\n"
"    <div class=\"pipeline-step\">Webcam</div>\n"
"    <span class=\"pipeline-arrow-h\">→</span>\n"
"    <div class=\"pipeline-step\">MediaPipe pose (33)</div>\n"
"    <span class=\"pipeline-arrow-h\">→</span>\n"
"    <div class=\"pipeline-step\">Skeleton extraction</div>\n"
"    <span class=\"pipeline-arrow-h\">→</span>\n"
"    <div class=\"pipeline-step\">Mesh binding</div>\n"
"    <span class=\"pipeline-arrow-h\">→</span>\n"
"    <div class=\"pipeline-step\">3D deformation</div>\n"
"    <span class=\"pipeline-arrow-h\">→</span>\n"
"    <div class=\"pipeline-step\">Rendered overlay</div>\n"
"    <span class=\"pipeline-arrow-h\">→</span>\n"
"    <div class=\"pipeline-step\">Display</div>\n"
"  </div>\n"
"\n"
"  <h2>Technical Highlights</h2>\n"
"\n"
"  <div class=\"highlight\">\n"
"    <div class=\"highlight-title\">1. Sparse-to-dense binding</div>\n"
"    <p>33 landmarks must drive a mesh with orders of magnitude more vertices. The binding weights determine how much each joint influences each vertex — wrong weights show up as fabric that tears at joints or bunches unnaturally.</p>\n"
"  </div>\n"
"\n"
"  <div class=\"highlight\">\n"
"    <div class=\"highlight-title\">2. Temporal stability</div>\n"
"    <p>MediaPipe landmark positions have sub-pixel noise between frames. Without temporal smoothing, the mesh jitters visibly even when the person holds still.</p>\n"
"  </div>\n"
"\n"
"  <div class=\"highlight\">\n"
"    <div class=\"highlight-title\">3. Real-time constraint</div>\n"
"    <p>Pose estimation + binding + render must complete in under 33ms per frame for 30fps. Each stage has a hard budget.</p>\n"
"  </div>\n"
"\n"
"  <div class=\"tech-stack\">\n"
"    <span class=\"pill\">MediaPipe</span>\n"
"    <span class=\"pill\">Python</span>\n"
"    <span class=\"pill\">3D rendering</span>\n"
"    <span class=\"pill\">Real-time CV</span>\n"
"  </div>\n"
"\n"
"  <hr class=\"section-divider\">\n"
"\n"
"  <!-- BOTTOM — Limitations -->\n"
"  <div class=\"limitations\">\n"
"    <h2>Limitations</h2>\n"
"    <ul>\n"
"      <li>Requires good, even lighting — shadows degrade pose estimation</li>\n"
"      <li>Front-facing optimized — side/back views are degraded</li>\n"
"      <li>Upper body only</li>\n"
"      <li>One hardcoded mesh — no garment selector yet</li>\n"
"      <li>Planning: catalogue UI + size estimation from landmark distances</li>\n"
"    </ul>\n"
"  </div>\n"
"\n"
"</div>\n"
"</body>\n"
"</html>\n"
;

const char *get_project_arshirt_html(void) {
    return project_arshirt_html;
}

