/* project_dlframework.c — Project HTML embedded in the kernel */

const char *project_dlframework_html =
"<!-- FILE: projects/dlframework/index.html -->\n"
"<!DOCTYPE html>\n"
"<html lang=\"en\">\n"
"<head>\n"
"<meta charset=\"UTF-8\">\n"
"<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
"<title>DistLearn — Distributed Training</title>\n"
"<style>\n"
"*, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }\n"
"body {\n"
"  font-family: 'Inter', system-ui, sans-serif;\n"
"  background: #0d0d0d;\n"
"  color: #e8e8e8;\n"
"  line-height: 1.65;\n"
"  overflow-y: auto;\n"
"  -webkit-font-smoothing: antialiased;\n"
"}\n"
"::selection { background: rgba(255,255,255,0.1); color: #fff; }\n"
"::-webkit-scrollbar { width: 5px; }\n"
"::-webkit-scrollbar-track { background: transparent; }\n"
"::-webkit-scrollbar-thumb { background: #2a2a2a; border-radius: 3px; }\n"
"\n"
".page { max-width: 720px; margin: 0 auto; padding: 32px 24px; }\n"
"\n"
"h1 { font-family: 'Inter', sans-serif; font-size: 32px; font-weight: 500; color: #e8e8e8; margin-bottom: 8px; }\n"
"h2 { font-family: 'Inter', sans-serif; font-size: 18px; font-weight: 500; color: #e8e8e8; margin-bottom: 16px; margin-top: 48px; }\n"
"p { font-size: 14.5px; color: #888888; line-height: 1.7; margin-bottom: 16px; }\n"
".claim { font-size: 15px; color: #888888; line-height: 1.6; margin-bottom: 20px; }\n"
"\n"
".metric-card {\n"
"  background: #1a1a1a; border: 1px solid #2a2a2a; border-radius: 8px;\n"
"  padding: 16px; display: inline-block; margin-bottom: 20px;\n"
"}\n"
".metric-value { font-family: 'JetBrains Mono', monospace; font-size: 28px; color: #e8e8e8; }\n"
".metric-label { font-family: 'Inter', sans-serif; font-size: 12px; color: #666666; margin-top: 4px; }\n"
"\n"
".badge-row { margin-bottom: 16px; }\n"
".badge {\n"
"  display: inline-block; background: #1e1e1e; border: 1px solid #333;\n"
"  border-radius: 4px; padding: 3px 10px; font-size: 12px;\n"
"  font-family: 'Inter', sans-serif; color: #888; margin-right: 6px; margin-bottom: 6px;\n"
"}\n"
".badge-muted {\n"
"  display: inline-block; background: transparent; border: 1px solid #2a2a2a;\n"
"  border-radius: 4px; padding: 3px 10px; font-size: 11px;\n"
"  font-family: 'Inter', sans-serif; color: #555; margin-bottom: 16px;\n"
"}\n"
"\n"
".callout {\n"
"  background: #141414; border-left: 3px solid #3b82f6;\n"
"  border-radius: 0 8px 8px 0; padding: 16px 20px; margin: 24px 0;\n"
"}\n"
".callout p { color: #888888; margin-bottom: 0; }\n"
".callout p + p { margin-top: 12px; }\n"
"\n"
".video-placeholder {\n"
"  background: #1a1a1a; border: 1px dashed #333; border-radius: 16px;\n"
"  padding: 56px 24px; text-align: center; margin: 24px 0;\n"
"}\n"
".video-placeholder .label { font-family: 'Inter', sans-serif; font-size: 14px; color: #555; }\n"
".video-placeholder .sublabel { font-family: 'Inter', sans-serif; font-size: 12px; color: #444; margin-top: 4px; }\n"
"\n"
"pre.diagram {\n"
"  font-family: 'JetBrains Mono', monospace; font-size: 13px;\n"
"  background: #141414; padding: 20px; border-radius: 8px;\n"
"  border: 1px solid #2a2a2a; overflow-x: auto; white-space: pre;\n"
"  color: #888; line-height: 1.5;\n"
"}\n"
"\n"
".diagram-note {\n"
"  font-family: 'Inter', sans-serif; font-size: 12px; color: #555;\n"
"  margin-top: 12px; line-height: 1.5;\n"
"}\n"
"\n"
".highlight { margin-bottom: 24px; }\n"
".highlight-title { font-family: 'Inter', sans-serif; font-size: 14px; font-weight: 500; color: #e8e8e8; margin-bottom: 6px; }\n"
".highlight p { font-size: 13.5px; color: #888; }\n"
"\n"
".tech-stack { margin: 32px 0; }\n"
".pill {\n"
"  display: inline-block; background: #1e1e1e; border: 1px solid #333;\n"
"  border-radius: 4px; padding: 3px 10px; font-size: 12px;\n"
"  font-family: 'Inter', sans-serif; color: #888; margin-right: 6px; margin-bottom: 6px;\n"
"}\n"
"\n"
".limitations { margin-top: 48px; }\n"
".limitations h2 { font-size: 14px; color: #555; text-transform: uppercase; letter-spacing: 1.5px; }\n"
".limitations ul { list-style: none; padding: 0; }\n"
".limitations li {\n"
"  font-size: 13.5px; color: #666; padding: 6px 0 6px 16px; position: relative; line-height: 1.5;\n"
"}\n"
".limitations li::before { content: \"—\"; position: absolute; left: 0; color: #444; }\n"
"\n"
".section-divider { border: none; border-top: 1px solid #1a1a1a; margin: 48px 0; }\n"
"</style>\n"
"</head>\n"
"<body>\n"
"<div class=\"page\">\n"
"\n"
"  <!-- LAYER 1 — Above the fold -->\n"
"  <h1>DistLearn</h1>\n"
"  <p class=\"claim\">Distributed training across personal devices — workers join and leave mid-run, training never stops, no sync barrier</p>\n"
"\n"
"  <div class=\"metric-card\">\n"
"    <div class=\"metric-value\">Async SGD</div>\n"
"    <div class=\"metric-label\">no synchronization barrier</div>\n"
"  </div>\n"
"\n"
"  <p>Most distributed training frameworks assume a fixed cluster. This one treats your personal devices as an opportunistic pool. A phone joins when it's idle. A laptop trains during lunch. Both can disconnect without stopping the run. The coordinator uses async SGD with staleness dropping — gradients are applied as they arrive, stale ones are discarded.</p>\n"
"\n"
"  <div class=\"badge-row\">\n"
"    <span class=\"badge\">Research Paper</span>\n"
"    <span class=\"badge\">Distributed Systems</span>\n"
"    <span class=\"badge\">PyTorch</span>\n"
"    <span class=\"badge\">FastAPI</span>\n"
"  </div>\n"
"  <div><span class=\"badge-muted\">Research prototype</span></div>\n"
"\n"
"  <hr class=\"section-divider\">\n"
"\n"
"  <!-- LAYER 2 — The Story -->\n"
"  <h2>Why async SGD and why staleness dropping</h2>\n"
"\n"
"  <div class=\"callout\">\n"
"    <p>PyTorch Distributed uses synchronization barriers — every worker must finish before the next step starts. That assumption breaks when workers are personal devices that sleep, lose WiFi, or run out of battery. Async SGD removes the barrier: the controller applies each gradient as it arrives (w = w − lr × gradient). But this creates a new problem — a gradient computed 50 steps ago on stale weights can push the model in the wrong direction. Staleness dropping solves this: the controller tracks gradient age and discards updates beyond a threshold.</p>\n"
"    <p>The result is a training run that degrades gracefully when devices leave and recovers automatically when they rejoin.</p>\n"
"  </div>\n"
"\n"
"  <div class=\"video-placeholder\">\n"
"    <span class=\"material-symbols-rounded\" style=\"font-size:48px;color:#444;display:block;margin-bottom:12px\">play_circle</span>\n"
"    <span class=\"label\">Demo video coming soon</span>\n"
"    <div class=\"sublabel\">Best demo is adding a phone mid-training and watching the loss curve continue uninterrupted</div>\n"
"  </div>\n"
"\n"
"  <hr class=\"section-divider\">\n"
"\n"
"  <!-- LAYER 3 — Architecture -->\n"
"  <h2>Architecture</h2>\n"
"\n"
"<pre class=\"diagram\">\n"
"┌──────────────────────────────────────────┐\n"
"│         Controller (FastAPI :8000)       │\n"
"│                                          │\n"
"│  Global model · Dataset · Gradient buf   │\n"
"│  POST /register                          │\n"
"│  GET  /get_task  (weights + batch)       │\n"
"│  POST /send_gradients                    │\n"
"└────────────────┬─────────────────────────┘\n"
"                 │\n"
"       ┌─────────┼─────────┐\n"
"       │         │         │\n"
"  ┌────┴───┐ ┌───┴───┐ ┌───┴───┐\n"
"  │Worker 1│ │Worker2│ │WorkerN│\n"
"  │ laptop │ │ phone │ │termux │\n"
"  │  k=120 │ │  k=40 │ │  k=?  │\n"
"  └────────┘ └───────┘ └───────┘\n"
"  (join or leave at any time — training continues)\n"
"</pre>\n"
"\n"
"  <p class=\"diagram-note\">k = local training steps. The controller estimates k per worker based on its reported CPU, RAM, and bandwidth — slow phones get fewer steps per round.</p>\n"
"\n"
"  <h2>Technical Highlights</h2>\n"
"\n"
"  <div class=\"highlight\">\n"
"    <div class=\"highlight-title\">1. Time-bounded computation</div>\n"
"    <p>k is not fixed globally. Each worker reports its compute + bandwidth on registration. The controller assigns a k that fills the worker's available time window — a phone might get k=40 while a laptop gets k=120. Same wall-clock time, different work.</p>\n"
"  </div>\n"
"\n"
"  <div class=\"highlight\">\n"
"    <div class=\"highlight-title\">2. Staleness dropping</div>\n"
"    <p>The controller tracks how many global steps have elapsed since a gradient was computed. Gradients older than the staleness threshold are discarded rather than applied — preventing stale updates from corrupting the model.</p>\n"
"  </div>\n"
"\n"
"  <div class=\"highlight\">\n"
"    <div class=\"highlight-title\">3. Android via Termux</div>\n"
"    <p>Workers run on Android phones without modification — just Termux + pip install. No special mobile build, no app store.</p>\n"
"  </div>\n"
"\n"
"  <div class=\"tech-stack\">\n"
"    <span class=\"pill\">Python</span>\n"
"    <span class=\"pill\">PyTorch</span>\n"
"    <span class=\"pill\">FastAPI</span>\n"
"    <span class=\"pill\">Uvicorn</span>\n"
"    <span class=\"pill\">Async SGD</span>\n"
"    <span class=\"pill\">Termux</span>\n"
"  </div>\n"
"\n"
"  <hr class=\"section-divider\">\n"
"\n"
"  <!-- BOTTOM — Limitations -->\n"
"  <div class=\"limitations\">\n"
"    <h2>Limitations</h2>\n"
"    <ul>\n"
"      <li>Tested only on MNIST / small CNNs — large models untested</li>\n"
"      <li>LAN only — workers must reach controller IP directly</li>\n"
"      <li>Gradient compression not implemented — bandwidth bottleneck</li>\n"
"      <li>Staleness threshold is hardcoded, not adaptive</li>\n"
"      <li>No multi-tenant support (one training run at a time)</li>\n"
"    </ul>\n"
"  </div>\n"
"\n"
"</div>\n"
"</body>\n"
"</html>\n"
;

const char *get_project_dlframework_html(void) {
    return project_dlframework_html;
}

